### ISSUE TITLE
The refined subset of 498 images

### ISSUE THREAD

**Issue by naifalshammari** [MartinHahner88/FoggySynscapes#1]
Dear Martin,

I'm wondering about the Foggy Cityscapes refined subset of **498** images you fine-tuned your model with if I can find the exact subset file list from the whole training set **2975**.

Best Regards,

Naif

**Comment by MartinHahner88** [comment]
Hi Naif, 

thank you for your interest in _Foggy Synscapes_.
Unfortunately, I don't have the exact indices anymore, but if you already have access to _Synscapes_,
you can send me an [email](mailto:martin.hahner@vision.ee.ethz.ch) and I can give you access to the images itself. 

Please attach image #23 of Synscapes ("23.png") as proof that you have access to the original dataset, otherwise, I am afraid I cannot share it with you because of the license agreement we signed.

Greets, Martin
